ynput/ayon-react-components

src/Dropdown/Dropdown.stories.tsx
src/Dropdown/Dropdown.tsx
src/Icon/Icon.tsx
src/Inputs/InputColor/InputColor.tsx
src/Layout/FormRow/FormRow.tsx
src/Panels/TablePanel/TablePanel.tsx

- Fixed a height issue
- Added default expand icon
- FormRow now has labelStyled and fieldStyled
- Fix InputColor returning strings in array of floats

fix: Dropdown fixes

---

src/Dropdown/DefaultValueTemplate.tsx
src/Dropdown/Dropdown.stories.tsx
src/Dropdown/Dropdown.tsx
src/Icon/Icon.tsx

- Improved the dropdown animation to be less jarrying and more sleek.
- Fixed some style issues where the options dropdown was 2px wider than the value button.
- Fixed an issue where an option value focussed outline was getting cut off at the top and bottom.

Cosmetic: improved dropdown animation

---

package.json
src/Inputs/InputDate/InputDate.scss
src/Inputs/InputDate/InputDate.stories.tsx
src/Inputs/InputDate/InputDate.tsx
src/Inputs/InputDate/index.tsx
src/index.tsx
yarn.lock

- React Datepicker from `react-datepicker`
- Custom styles

feature: InputDate

---

src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
src/Dropdowns/Dropdown/Dropdown.stories.tsx
src/Dropdowns/Dropdown/Dropdown.tsx
src/Dropdowns/TagsSelect/TagsSelect.tsx
src/Dropdowns/TagsSelect/TagsSelectValueTemplate.tsx

- extended more props that can be accessed.
- fixed a couple issues
- set default background to input color
- new prop `buttonStyle` to access background color, hover color etc.
- new className props for button, value, list, item.

chore: more dropdown props and controls

---

src/FileCard/FileCard.tsx
src/FileUpload/FileUpload.stories.tsx
src/FileUpload/FileUpload.tsx
src/FileUpload/filesData.ts

- readOnly
- message on file for errors
- custom header and footer props
- more... I will fill in later

enhancement: file upload readonly, failed message and custom header/footer

---

src/Inputs/InputSwitch/InputSwitch.styled.ts
src/Layout/OverflowField/OverflowField.stories.tsx
src/Layout/OverflowField/OverflowField.styled.ts
src/Layout/OverflowField/OverflowField.tsx
src/index.scss
src/primereact/theme.sass

- Improved colors
- Doubled animation speed
- Tweaked animation

fix: improved switch colors

---

package.json
src/Dropdowns/Dropdown/Dropdown.stories.tsx
src/Dropdowns/Dropdown/Dropdown.tsx
src/FileUpload/FileUpload.tsx
src/Inputs/InputSwitch/InputSwitch.stories.tsx
src/Inputs/InputSwitch/InputSwitch.styled.ts
src/Inputs/InputSwitch/InputSwitch.tsx

- Fix an issue in FileUpload where dragging and dropping files in a random order fails to create a sequence.
- Fix an issue in Dropdown where at the bottom of the screen the dropdown options would jump up to a random location.
- Bump `0.5.3`

Fixes: Dropdown position and FileUpload sorting bug

---

package.json
src/EntityCard/EntityCard.stories.tsx
src/EntityCard/EntityCard.styled.ts
src/EntityCard/EntityCard.tsx

- New prop `isFullHighlight` will highlight full card when `isActive`.
- Fix: Improved loading styles and more shimmer 👐

Enhancement: entity card full selection

---

src/Dropdowns/Dropdown/Dropdown.tsx

- Fixes #63  searching wouldn't allow hitting space bar.
- Fixes #65 creating new items now splits items by comma `,`

Dropdown search and adding

---

package.json
src/Inputs/styles.tsx

- removed fixed width from password input

fix: removed fixed width for input

---

package.json
src/Overlay/Dialog/Dialog.stories.tsx
src/Overlay/Dialog/Dialog.styled.ts
src/Overlay/Dialog/Dialog.tsx

- added switch between dialog/modal for Dialog component
- this supports native differences between two types of Dialog element
- also partially helps solving issue with dropdown on NewSequence and NewEntity in ayon-frontend

79 dialog implementation fixes

---

package.json
src/Overlay/Dialog/Dialog.tsx

- added switch between dialog/modal for Dialog component
- this supports native differences between two types of Dialog element
- also partially helps solving issue with dropdown on NewSequence and NewEntity in ayon-frontend

release 1.0.3

---

src/Overlay/Dialog/Dialog.stories.tsx
src/Overlay/Dialog/Dialog.tsx

- added onShow property for modal (example: for automatic opening for dropdowns)

hotfix: added onShow property for modal

---

src/Dropdowns/Dropdown/DefaultValueTemplate.tsx
src/Dropdowns/Dropdown/Dropdown.tsx

Add dropdown props `clearTooltip` and `clearNullTooltip`

Release: 1.0.12

---

src/Dropdowns/Dropdown/DefaultValueTemplate.tsx
src/Dropdowns/Dropdown/Dropdown.stories.tsx
src/Dropdowns/Dropdown/Dropdown.tsx

You can now do this and returning null will use default value template:
```jsx
valueTemplate={(value, selected, isOpen) =>
selected.length >= truncateAt ? (
<IconsTemplate {...props} {...{ value, selected, isOpen }} />
) : null
}
```

Release 1.0.13

---

src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx

fix(AssigneeSelect): Read only not receiving all props

Release: 1.0.14

---

src/EntityCard/EntityCard.tsx

fix(EntityCard): ensure image always loads in

Release: 1.0.16

---

src/EntityCard/EntityCard.tsx

fix(EntityCard): wrong image loading state

Release: 1.1.2

---

src/EntityCard/EntityCard.styled.ts

fix(entity card): images have a background

release: 1.1.3

---

src/Dropdowns/AssigneeSelect/AssigneeField.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx

AssigneeSelect readonly alignment

Release: 1.1.4

---

src/Dropdowns/AssigneeSelect/AssigneeDropdownTemplate.tsx
src/Dropdowns/AssigneeSelect/AssigneeField.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
src/Dropdowns/Dropdown/Dropdown.stories.tsx
src/Dropdowns/Dropdown/Dropdown.tsx

Ability to select/deselect all items in a dropdown.
AssigneeSelect supports selecting all users.
New props
- `onSelectAll: (selected: string[]) => void | boolean`
- `selectAllKey: string = '__all__'`

Dropdown: select all and Assignees select all

---

src/Dropdowns/AssigneeSelect/AssigneeDropdownTemplate.tsx
src/Dropdowns/AssigneeSelect/AssigneeField.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
src/Dropdowns/Dropdown/Dropdown.stories.tsx
src/Dropdowns/Dropdown/Dropdown.tsx
src/EntityCard/EntityCard.styled.ts

Release: 1.1.5

---

src/EntityCard/EntityCard.stories.tsx
src/EntityCard/EntityCard.styled.ts

EntityCard: Increase selection brightness

---

src/Button/Button.stories.tsx
src/Button/Button.styled.ts
src/Button/Button.tsx
src/ShortcutTag/ShortcutTag.stories.tsx
src/ShortcutTag/ShortcutTag.tsx

- Added new `ShortcutTag` component.
- Integrated `ShortcutTag` into `Button`.

Shortcut component

---

src/FileCard/FileCard.tsx
src/index.tsx

Release 1.3.6

---

src/FileCard/FileCard.tsx
src/index.tsx

release: 1.3.6

---

src/Dropdowns/AssigneeSelect/AssigneeDropdownTemplate.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
src/Dropdowns/Dropdown/Dropdown.tsx

Dropdown: AssigneeSelect missing users

---

src/Dropdowns/AssigneeSelect/AssigneeDropdownTemplate.tsx
src/Dropdowns/AssigneeSelect/AssigneeField.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
src/Dropdowns/Dropdown/Dropdown.stories.tsx
src/Dropdowns/Dropdown/Dropdown.styled.ts
src/Dropdowns/Dropdown/Dropdown.tsx
src/Dropdowns/StatusSelect/StatusSelect.tsx
src/Dropdowns/VersionSelect/VersionSelect.tsx
src/Dropdowns/WatcherSelect/WatcherSelect.tsx
src/EntityCard/EntityCard.tsx

Dropdown new props
```typescript
multipleOverride?: boolean  multiSelect: boolean
onAddItem?: (v: string) => void
onRemoveItem?: (v: string) => void
```

Assignee Select: ability to remove users when mixed

---

src/Dropdowns/AssigneeSelect/AssigneeDropdownTemplate.tsx
src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
src/Dropdowns/Dropdown/Dropdown.tsx

-   [ ] This comment contains a description of changes
-   [ ] Referenced issue is linked

fix(Dropdown): mixed override show remove icon

---

README.md

Add missing step `yarn install` in get started section.

Add missing step in get started section

---

package.json
src/SearchFilter/SearchFilter.stories.tsx
src/SearchFilter/SearchFilter.styled.ts
src/SearchFilter/SearchFilter.tsx
src/SearchFilter/SearchFilterDropdown/SearchFilterDropdown.styled.ts
src/SearchFilter/SearchFilterDropdown/SearchFilterDropdown.tsx
src/SearchFilter/SearchFilterItem.tsx
src/SearchFilter/SearchFilterItemValue.tsx
src/SearchFilter/buildFilterId.ts
src/SearchFilter/checkColorBrightness.ts
src/SearchFilter/doesFilterExist.ts
src/SearchFilter/getFilterFromId.ts
src/SearchFilter/hooks.ts
src/SearchFilter/index.tsx
src/SearchFilter/types.ts

Component: Search filter
