src/app.jsx, src/components/index.js, src/components/input/colorPicker.jsx, src/components/input/index.jsx, src/components/overlay/dialog.jsx, src/helpers/floatToInt8.js, src/helpers/hexToFloat.js, src/helpers/int8ToHex.js, src/helpers/toHexColor.js, src/helpers/validateHexColor.js
A color picker preview and dialog with different formats and alpha support.
A fully custom color dialog that supports the `value` `hex | float | uint8 | unit16` and an optional `alpha`  boolean.
The preview button shows the selected color state and if it has an alpha. The alpha is always represented as a float between 0-1. For hex formats the alpha float is converted to a hex string and concatenated. `#c600ff + 0.5` -> `#c600ff80`. For all other formats it is represented as a 4th float in the array `[255, 134, 90, 0.5]`.
Color Value is returned as an object (e.target.value) to be more consistent with other inputs.
The Demo Form has been updated to show different colours in different formats to make testing different combinations easier.
- A color input picker to allow for quicker and …
=> UX Element: Color Picker Dialog

src/components/button/colorPickerPreview.jsx, src/components/input/colorPicker.jsx, src/components/overlay/dialog.jsx, src/helpers/floatToInt16.js
Include the native color picker input as an easy way to pick a quick color.
A custom "color preview" component has been created to show the selected color and alpha whilst also acting as a color picker input for fast color selection.
- Confirmation buttons added
- Picker uses "basic" mode when format is `hex | uint8` and `alpha = false`.
- Pasting in whole colors difficult. (Paste in 255,234,123)
- Buttons aren't included in tab index for safari
=> Enhancement: Color Picker Quick Select

src/components/input/colorPicker.jsx
Color wasn't updating when it's `value` prop changed, fixed now.
Switch between projects, the ColorPicker won't unmount/remount but the color should still update.
Ensure making changes to the color updates the state for the correct project.
=> FIX: Update color when Value prop changes

src/components/input/colorPicker.jsx
Hitting the enter key on any of the dialog inputs will confirm and close the dialog. 
Moved back to using Prime-React dialog (for now) as it automatically handles "esc" as well. It should also hopefully fix the collapsing of the menu item. Although I think this is a bug that happens in not just the Color Picker.
=> FIX: Close picker on enter key

src/components/Dropdown.jsx, src/input.jsx
When the search prop is enabled on a dropdown, a new maxOptionsShown prop with a default value of 25 will be activated. 
This feature limits the number of rendered items to improve performance. 
Items that exceed this maximum will not be rendered in the DOM, but can still be searched for and selected.
=> fix: set max dropdown items when searching

src/Dropdown/Dropdown.tsx
Fix an issue where selecting multiple inputs and then selecting the original (already selected) value wouldn't make any changes.
=> fix: isMultiple same value blocked

src/Dropdowns/Dropdown/DefaultValueTemplate.tsx, src/Dropdowns/Dropdown/Dropdown.tsx
Use case: set a field with list of strings to `null` instead of `[]` to set inheritance from parent.
=> fix: onClearNoValue prop to show clear button even with no value

package.json, src/Button/Button.tsx, src/Dropdowns/AssigneeSelect/AssigneeField.tsx, src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx, src/Dropdowns/Dropdown/Dropdown.styled.ts, src/EntityCard/EntityCard.stories.tsx, src/EntityCard/EntityCard.styled.ts, src/EntityCard/EntityCard.tsx, src/Inputs/InputSwitch/InputSwitch.styled.ts, src/User/UserImage/UserImage.styled.ts, src/User/UserImage/UserImage.tsx, src/User/UserImagesStacked/UserImagesStacked.tsx, src/helpers/getRandomImage.ts, src/index.scss
- Switch disabled styles
- AssigneeSelect `emptyIcon` prop now takes icon or null to remove icon.
- Fixed initials colour issue on UserImage
- Added classnames to UserImage
- Dropdown height 30px to 32px
- EntityCard now supports assignees images in the bottom right corner
- EntityCard border from 4px to 2px
- Button now accepts `iconProps` prop
- Bumped version
=> Fixes: entity card, switch, assignee select

package.json, src/Layout/TableRow/TableRow.stories.tsx, src/Layout/TableRow/TableRow.tsx
- Use a check and close icon for boolean attributes instead of a disabled switch.
- Bump 0.4.18
=> TableRow: boolean check instead of switch

package.json, src/Dropdowns/Dropdown/Dropdown.stories.tsx, src/Dropdowns/Dropdown/Dropdown.styled.ts, src/Dropdowns/Dropdown/Dropdown.tsx
- Changed the animation to be simpler and faster.
- Use `createPortal` to place open options dialog inside of `document.body` so that it's always on top and never cutoff.
- Use custom overlay scrollbar.
- BREAKING: Removed `openOnFocus` prop.
- BREAKING: `ref` prop changed to expose `getElement`, `getOptions`, `open` and `hide`.
- Bump: `0.5.0`
```typescript
export interface DropdownRef {
getElement: () => HTMLDivElement | null
getOptions: () => HTMLUListElement | null
open: () => void
close: () => void
}
```
=> Dropdown: Animation rewrite

src/Dropdowns/Dropdown/DefaultValueTemplate.tsx, src/Dropdowns/Dropdown/Dropdown.stories.tsx, src/Dropdowns/Dropdown/Dropdown.styled.ts, src/Dropdowns/Dropdown/Dropdown.tsx, src/Dropdowns/Dropdown/TagsValueTemplate.tsx
- BREAKING: `onClearNoValue` renamed to `onClearNullValue` and behaviour changed to enable/disable setting value as `null`.
- Dropdown now supports null values and will show a default `(no value)` placeholder unless a custom one is provided.
- `onClearNullValue` along with `onClear` reveals new backspace icon to set the value to `null` instead of the default clear value of `[]`
- `nullPlaceholder` prop allows for custom null placeholder text.
- `onClear` function prop will now provide a clearing value of either `null` or `[]` 
https://github.com/ynput/ayon-react-components/assets/49156310/37a4ebae-c8ae-4e5b-8fe4-57ab6be7efd8
=> Enhancement: dropdown null and invalid values

package.json, src/Dropdowns/Dropdown/DefaultValueTemplate.tsx, src/Dropdowns/Dropdown/Dropdown.stories.tsx, src/Dropdowns/Dropdown/Dropdown.tsx, src/Dropdowns/IconSelect/IconSelect.tsx, src/Dropdowns/SortingDropdown/SortingDropdown.tsx, src/Dropdowns/TagsSelect/TagsSelectValueTemplate.tsx
- `onClear` and `onClearNull` now operate independently. So you can have either one or both.
- Type fixes.
=> Fix: Dropdown separate clear null

package.json, src/Dropdowns/Dropdown/Dropdown.stories.tsx, src/Dropdowns/Dropdown/Dropdown.tsx
- New prop `onSelectionChange` prop that works the same way as `onChange` but fires every time the selection changes, even before the dropdown has closed.
- Bump: version 0.5.7
=> Dropdown onSelectionChange

src/Dropdowns/TagsSelect/TagsSelect.tsx
- Brackets in tags did not appear when they had mixed value, turns out one property was not being properly passed down
https://github.com/ynput/ayon-react-components/assets/16327908/75992f09-3d52-42c4-b2e6-3f1b94305251
=> Fix: Fixed brackets for mixed tags

src/EntityCard/EntityCard.styled.ts, src/EntityCard/EntityCard.tsx
- Fix: image/icon was not showing when component was unmounting and then remounting.
- Fix: reduce the transition time for fading in the image.
=> Fix: entity card image not showing

src/Inputs/InputNumber/InputNumber.tsx, src/Inputs/InputPassword/InputPassword.stories.tsx, src/Inputs/InputPassword/InputPassword.tsx, src/Inputs/InputText/InputText.stories.tsx, src/Inputs/InputText/InputText.tsx, src/Inputs/styles.tsx
This is solution to issue reported originally in ayon-frontend repository
https://github.com/ynput/ayon-frontend/issues/332
- I have updated input component so that there is switch for hiding characters.
- Originally, this was required only for input type="password", however, some of the required places have input type="text"
- Rather than changing type of  from text to password, I have added CSS property for text input that can hide characters
- Hiding characters for input type="text" may not be working for IE - https://caniuse.com/?search=text-security
Result:
- Now hiding works for both types (text and password), logic is slightly different though
- Hiding is optional (both text and password input can be with or without toggling icon and logic)
Password: …
=> enhancement: added switch for showing/hiding characters in password + textinput

src/Dropdowns/Dropdown/Dropdown.stories.tsx, src/Dropdowns/Dropdown/Dropdown.tsx, src/Overlay/Dialog/Dialog.stories.tsx, src/Overlay/Dialog/Dialog.styled.ts, src/Overlay/Dialog/Dialog.tsx
- added Dropdown isPortal switch - for using dropdown in NewEntity and NewSequence in ayon-frontend
- portal is by default set to true (i.e. Dropdowns will be generated through portal unless explicitly set isPortal to false)
- heading font increase
- cancel button text render fix
- X button padding error fix (text could overlap with X button before)
Closes #79
=> 79 dialog implementation fixes

src/Overlay/Dialog/Dialog.stories.tsx, src/Overlay/Dialog/Dialog.styled.ts, src/Overlay/Dialog/Dialog.tsx
Currently there are two buttons that do the same thing, the top right close icon and the bottom footer cancel button.
I think the cancel button can be hidden by default unless specified, the majority of cases don't require it.
=> fix: hide close button by default

src/Dropdowns/Dropdown/Dropdown.stories.tsx, src/Dropdowns/Dropdown/Dropdown.tsx
- Reverts a commit that would give you an option to not use the portal. It was causing re-rendering issues with the keyboard.
https://github.com/ynput/ayon-react-components/assets/49156310/3df5429a-1701-453a-aa35-8e9ee6a3d22a
- Fixes a bug that meant scrolling with the keyboard didn't work.
=> Dropdown: re-rendering bug and fixes

src/Dropdowns/Dropdown/Dropdown.tsx, src/Overlay/Dialog/Dialog.stories.tsx, src/Overlay/Dialog/Dialog.styled.ts, src/Overlay/Dialog/Dialog.tsx
The `dialog` tag has caused all sorts of problems with little upsides. Let's use the `div` tag instead and build some of the default properties the `dialog` tag had.
=> Dialog: used div instead of dialog tag

src/Overlay/Dialog/Dialog.styled.ts
Backdrop was not overlaying through all elements in ayon-frontend, I added z-index.
=> fix: added z-index for backdrop in Dialog

src/Overlay/Dialog/Dialog.stories.tsx, src/Overlay/Dialog/Dialog.tsx
-   [ ] Added switch for backdrop
-   [ ] relates to issue from ayon-frontend https://github.com/ynput/ayon-frontend/issues/334
- for some instaces we migth need dialog with no backdrop
- currently for adding new teams https://github.com/ynput/ayon-frontend/issues/334
- added isBackdrop prop that is set to true by default
https://github.com/ynput/ayon-react-components/assets/16327908/bb9bf9e1-b3e1-43d6-accb-c682d055eb2f
=> enhancement:  added no backdrop option for dialog

src/Overlay/Dialog/Dialog.stories.tsx
-   [x] Dialog is in the center of the screen.
-   [x] Clicking on backdrop closes dialog but clicking on dialog doesn't.
-   [x] Overflow content is not blurry.
Uses flexbox to center the dialog instead of
```css
position: fixed;
left: 50%;
top: 50%;
transform: translate(-50%, -50%);
```
Also changed prop name `isBackdrop=true` to `hideBackdrop=false`
=> chore(dialog): better scroll story

src/Overlay/Dialog/Dialog.tsx
- Dialog: custom portalRef, then root, then document.body
=> release: 1.0.11

src/Dropdowns/AssigneeSelect/AssigneeField.tsx, src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx, src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
- When no users are assigned the first selection of a user will close the dropdown straight away.
This was surprisingly easy. All I needed to do was set `multiSelect={value.length}`. When there's no value it acts like a single select and when there's at least one user, it acts like a multiselect.
https://github.com/ynput/ayon-react-components/assets/49156310/66eda9ce-31a7-459f-b500-6926c5d6ae2d
=> Assignee Select: setting first assignee closes dropdown automatically

src/Dropdowns/Dropdown/DefaultValueTemplate.tsx, src/Dropdowns/Dropdown/Dropdown.stories.tsx, src/Dropdowns/Dropdown/Dropdown.styled.ts, src/Dropdowns/Dropdown/Dropdown.tsx
- Show a warning when there are values without options.
- New error message prop
- Automatically show the search after 20 options (can be disabled with `search=false` or `searchOnNumber=200`)
- Automatically scroll and focus first selected item.
- New prop `activateKeys` to define which keys can open the dropdown.
=> Dropdown: Missing values warning

src/Dropdowns/AssigneeSelect/AssigneeField.tsx, src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx, src/EntityCard/EntityCard.stories.tsx, src/EntityCard/EntityCard.styled.ts, src/EntityCard/EntityCard.tsx, src/User/UserImage/UserImage.styled.ts, src/User/UserImage/UserImage.tsx, src/User/UserImagesStacked/UserImagesStacked.tsx
- New prop: `hidePriority` to explicitly hide the priority and make users width dynamic.
- New prop: `project` shown alongside `path` when hovering.
- New prop: `statusMiddle` now by default status is positioned bottom right but can be positioned to the middle.
- Default layout has changed with status bottom right and priority right of users.
- Using custom styling for stacked users to make it more condensed.
- When `users` props is empty list `[]` show an icon to add assignees. `users=undefined | null` will hide tag completely.
- Invert status tag colour to have status colour as the background.
=> Entity card fixes

src/Dropdowns/EnumDropdown/EnumDropdown.stories.tsx, src/Dropdowns/EnumDropdown/EnumDropdown.styled.ts, src/Dropdowns/EnumDropdown/EnumDropdown.tsx, src/Dropdowns/EnumDropdown/index.tsx, src/Dropdowns/IconSelect/IconSelect.stories.tsx, src/Dropdowns/IconSelect/IconSelect.styled.ts, src/Dropdowns/IconSelect/IconSelect.tsx, src/index.tsx
This pull request introduces a new `EnumDropdown` component with corresponding stories, styles, and exports. Additionally, it includes minor updates to the `IconSelect` component to improve consistency and functionality.
- Dropdown that supports, value, label, icon and color.
- Pass `colorInverse` prop to show the color as a bg color.
- Fixes the styles so that there is a dropdown icon.
=> Dropdown: EnumDropdown supports colors and icons

src/FileUpload/FileUpload.tsx
Allowing for custom components injection in the FileUpload component instead of the title.
They would show up on the left side of the actions header, i.e. the "Manage uploads" button in the screenshot below:
=> FileUpload - extra headers options to allow for custom elements in header bar

.storybook/preview.ts, src/SearchFilter/SearchFilter.stories.tsx, src/SearchFilter/SearchFilter.styled.ts, src/SearchFilter/SearchFilter.tsx, src/SearchFilter/SearchFilterDropdown/SearchFilterDropdown.styled.ts, src/SearchFilter/SearchFilterDropdown/SearchFilterDropdown.tsx, src/SearchFilter/types.ts
- Default option to show all child options when searching.
- Hitting enter with keyboard didn't work
- Going would back hide the option you went back from
- Options to change the text search label and icon
- Clicking on search bar again closes the dropdown
=> Search filter improvements
